### ISSUE TITLE
Integrate Travis-CI

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnack#17]
.travis.yml:
```yaml
sudo: false

language: java
jdk: oraclejdk8

cache:
  directories:
    - "$HOME/.cache"

notifications:
  email: false
```
