### ISSUE TITLE
Integrate Codecov

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnack#18]
pom.xml:
https://github.com/codecov/example-java-maven/blob/master/pom.xml#L47-L58

.travis.yml:
```yaml
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
```
