### ISSUE TITLE
Integrate Better Code

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnack#20]
.bettercodehub.yml:
```yaml
component_depth: 6
languages:
  - java
```
