### ISSUE TITLE
Integrate Zappr

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnack#21]
.zappr.yml:
```yaml
commit:
  message:
    patterns:
      - "^#[0-9]+ - "
specification:
  body:
    contains-issue-number: true
   template:
     differs-from-body: true
```
