### ISSUE TITLE
Integrate AppVeyor

### ISSUE THREAD

**Issue by GlennKintscher** [KatastrophenTeam/BreaktimeSnack#22]
.appveyor.yml:
```yaml
version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: choco install maven -y -f
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package --batch-mode -DskipTest
test_script:
  - mvn clean install --batch-mode
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
```
