### ISSUE TITLE
Convert Character Textfiles into YAML

### ISSUE THREAD

**Issue by BodooKing** [KatastrophenTeam/BreaktimeSnack#6]
- [x] Bowser
- [x] Captain Falcon
- [x] Donkey Kong
- [x] Dr. Mario
- [x] Falco
- [x] Fox
- [x] Ganondorf
- [x] Ice Climbers
- [x] Jigglypuff
- [x] Kirby
- [x] Link
- [x] Luigi
- [x] Marth
- [x] Mewtwo
- [x] Mr. Game & Watch
- [x] Ness
- [x] Sheik
- [x] Peach
- [x] Pichu
- [x] Pikachu
- [x] Roy
- [x] Samus
- [x] Yoshi
- [x] Young Link
- [x] Zelda

**Comment by GlennKintscher** [comment]
Waiting for changes by @BodooKing

**Comment by GlennKintscher** [comment]
Example file:

```yaml
Name: "Donkey Kong"
Trophies:
  - "4": "While he now prefers the laid-back jungle lifestyle to construction site mischief, DK is often forced back into action by the Kremlin Krew.
          The great ape is quite fast despite his burly physique, and he keeps his strength up with a steady diet of his favorite food: bananas.
          His one extravagance (and only piece of clothing) is a monogrammed necktie."
  - "5": "Donkey Kong is a huge target in a fight, so he hates crowds. When he's in the fray, his Giant Punch deals serious damage to multiple opponents.
          The big ape's Headbutt hits so hard that it temporarily buries opponent's in the ground.
          DK is a lot faster than he looks, and he's lethal in the hands of a master."
  - "6": "Being the strongest simian around, DK has the upper hand once he grabs an opponent.
          He can even lift his foe up and make him or her an unwilling traveling companion; if DK grabs you, shake your Control Stick as fast as you can to break his grip.
          His Spinning Kong covers more lateral distance than vertical, so use it quickly to recover."
Attacks:
  Standing:
    - "Swipe": "A"
    - "Uppercut": "A, A"
    - "Konga Kick": "[Dash] A"
  Jumping:
    - "Kong Whirl": "[Air] A"
    - "Hammer Knuckle": "[Air] RightArrow + A"
    - "Back Kick": "[Air] LeftArrow + A"
    - "Flying Headbutt": "[Air] UpArrow + A"
    - "Flying Stomp": "[Air] DownArrow + A"
  Strong:
    - "Backhand Slap": "RightArrow or LeftArrow + A"
    - "Backhand Slap (High)": "UpRightArrow + A"
    - "Backhand Slap (Low)": "DownRightArrow + A"
    - "Spider Web Swipe": "Up + A"
    - "Slouch Slap": "Down + A"
  Smash:
    - "Kong Klap": "Tap RightArrow or LeftArrow + A"
    - "Twin Beat": "Tap DownArrow + A"
    - "Ape Applause": "Tap UpArrow + A"
  Special:
    - "Giant Punch": "B"
    - "Headbutt": "RightArrow or LeftArrow + B"
    - "Spinning Kong": "UpArrow + B"
    - "Hand Slap": "DownArrow + B"
  Throws:
    - "Grab": "R + A"
    - "Jungle Chop": "R + A, A"
    - "Kong Karry": "R + A, RightArrow"
    - "Donkey Fling": "R + A, LeftArrow"
    - "Coconut Toss": "R + A, UpArrow"
    - "Simiam Slam": "R + A, DownArrow"
Taunt:
  "Huh?": "UpArrow on + Control Pad"
```
